gzip: fix -l bug with multimember files
Problem reported by Antonio Diaz Diaz in:
https://lists.gnu.org/r/bug-gzip/2024-01/msg00000.html
* NEWS: Mention this.
* gzip.c (treat_stdin, treat_file): Do not clear bytes_out.
* tests/list: Test for the bug.
* unpack.c (unpack):
* unzip.c (unzip):
Do not assume bytes_out is initially zero.

diff --git a/tests/list b/tests/list
--- a/tests/list
+++ b/tests/list
@@ -28,4 +28,13 @@ gzip -l in.gz >out1 || fail=1
 gzip -l in.gz | cat >out2 || fail=1
 compare out1 out2 || fail=1
 
+echo '' >small || framework_failure_
+gzip small || fail=1
+cat small.gz small.gz >smallx2.gz || framework_failure_
+gzip -l smallx2.gz >smallout || fail=1
+case $(cat smallout) in
+  *' 2 '*' smallx2') ;;
+  *) cat smallout; fail=1;;
+esac
+
 Exit $fail
